config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

	root 'home#index'
	get 'logout' => 'sessions#destroy', :as => 'logout'

	resources :signup, :only => [:new, :create]

	resources :sessions, :only => [:new, :create]

	resources :users, :except => [:index, :new] do
		resources :expenses, :except => [:index, :new] do
			collection do
				get :filter
			end
		end

		member do
			get :report
			get :user_details
		end
	end

	#API
	namespace :api, :defaults => { :format => 'json'} do
		scope module: :v1, :constraints => ApiConstraints.new(version: 1, default: true) do

			resources :sessions, :only => [:create, :destroy]

			resources :users, :except => [:new, :edit] do

				collection do
					get :loggedin_user
				end

				resources :expenses, :except => [:new, :edit] do
					collection do
						get :filter
					end
				end

				member do
					get :report
				end
			end

		end
	end

end

app/controllers/signup_controller.rb
class SignupController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(signup_params)

		if @user.save
			flash[:notice] = "Congratulations, you've created your account successfully!"
			redirect_to new_session_path
		else
			flash.now[:error] = "Error: #{@user.errors.full_messages.to_sentence}"
			render "new"
		end
	end

	private

	def signup_params
		params.permit(*policy(User).user_attributes)
	end


end

app/views/signup/new.html.erb
<%= javascript_include_tag "signup/signup_validation" %>

<div class="container">

<%= form_tag  signup_index_path(), :id => 'registration_form', :method => :post do %>
	<div class="col-sm-8 col-lg-8 col-md-8 col-md-offset-4" style="padding-bottom: 30px;">
	<br/><br/>
		<div class="row">
			<div class="col-md-6 form-group">
				<%= label_tag(:first_name, "First Name") %>
				<div class="input-group">
					<span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
					<%= text_field_tag(:first_name, @user.first_name, :class => 'form-control', :placeholder => 'First Name') %>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6 form-group">
				<%= label_tag(:last_name, "Last Name") %>
				<div class="input-group">
					<span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
					<%= text_field_tag(:last_name, @user.last_name, :class => "form-control", :placeholder => 'Last Name') %>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6 form-group">
				<%= label_tag(:email, "Email") %>
				<div class="input-group">
					<span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
					<%= text_field_tag(:email, @user.email, :class => 'form-control', :placeholder => 'user@isp.net') %>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6 form-group">
				<%= label_tag(:password, "Password") %>
				<div class="input-group">
					<span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
					<%= text_field_tag(:password, @user.password, :class => 'form-control', :placeholder => 'minimum length: 4 chars', :type => 'password') %>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6 form-group">
				<%= label_tag(:password_confirmation, "Password Confirmation") %>
				<div class="input-group">
					<span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
					<%= text_field_tag(:password_confirmation, @user.password_confirmation, :class => 'form-control', :placeholder => 'minimum length: 4 chars', :type => 'password') %>
				</div>
			</div>
		</div>
		<br/>

		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<div class="text-center">
						<%= button_tag( "Finish", :class => "btn btn-primary btn-sm" ) %>
					</div>
				</div>
			</div>
		</div>

	</div>
<% end %>

</div>