config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

	root 'home#index'
	get 'logout' => 'sessions#destroy', :as => 'logout'

	resources :signup, :only => [:new, :create]

	resources :sessions, :only => [:new, :create]

	resources :users, :except => [:index, :new] do
		resources :expenses, :except => [:index, :new] do
			collection do
				get :filter
			end
		end

		member do
			get :report
			get :user_details
		end
	end

	#API
	namespace :api, :defaults => { :format => 'json'} do
		scope module: :v1, :constraints => ApiConstraints.new(version: 1, default: true) do

			resources :sessions, :only => [:create, :destroy]

			resources :users, :except => [:new, :edit] do

				collection do
					get :loggedin_user
				end

				resources :expenses, :except => [:new, :edit] do
					collection do
						get :filter
					end
				end

				member do
					get :report
				end
			end

		end
	end

end

app/models/user.rb
class User < ActiveRecord::Base

	#attributes: email, first_name, last_name, :password_digest, role_id, auth_token, api_token

	has_secure_password

	#associations
	belongs_to :role
	has_many :expenses, :dependent => :destroy

	#validations
	validates :first_name, :last_name, :email, :role_id, :presence => true
	validates :email, :uniqueness => true
	validates_formatting_of :email, :using => :email
	validates :password, :presence => true, :length => { :within => 4..15 }, :if => :validate_password?

	#callbacks
	before_create :init_user
	before_validation :do_before_save


	def reset_api_token
		self.api_token = SecureRandom.urlsafe_base64
		true
	end

	private

	def init_user
		self.auth_token = SecureRandom.urlsafe_base64
		self.api_token = SecureRandom.urlsafe_base64
		true
	end

	def do_before_save
		if self.email_changed?
			self.email.strip!
			self.email.downcase!
		end
	end

	def validate_password?
		@force_password_verification || new_record? || !password.blank?
	end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApplicationController

	skip_before_action :authenticate_user, :only => :create
	#before_action :set_cors, :only => [:create, :loggedin_user]

	def create
		@user = User.new(user_params)

		if @user.save
			render 'create.json.jbuilder', :status => 201
		else
			render :json => { :message => @user.errors.full_messages.to_sentence }, :status => 409
		end
	end

	def update
		@user = User.find(params[:id])
		authorize @user

		if @user.update_attributes(user_params)
			render 'update.json.jbuilder', :status => 200
		else
			render :json => { :message => @user.errors.full_messages.to_sentence }, :status => 409
		end
	end

	def destroy
		@user = User.find(params[:id])
		authorize @user

		if @user.destroy
			render :json => { :message => "User deleted"}, :status => 200
		else
			render :json => { :message => @user.errors.full_messages.to_sentence }, :status => 409
		end
	end

	def show
		@user = User.find(params[:id])
		authorize @user
		render 'show.json.jbuilder', :status => 200
	end

	def index
		@users = User.all
		authorize @users
		render 'index.json.jbuilder', :status => 200
	end

	def report
		@user = User.find(params[:id])
		authorize @user

		data = ReportService.generate_report_data(params, @user)

		if data.nil?
			render :json => { :message => "Wrong params"}, :status => 400
		else
			if request.headers['Accept'] && (request.headers['Accept'] == 'application/pdf' || request.headers['Accept'] == 'application/octet-stream')
				send_data ReportService.generate_pdf(data), filename: APP_CONFIG['report_file_name'], type: 'application/pdf', :status => 200
			else
				send_data data, filename: APP_CONFIG['report_file_name'], type: 'json', :status => 200
			end
		end
	end

	def loggedin_user
		@user = User.find_by_api_token(request.headers["api-token"])
		authorize @user

		render 'loggedin_user.json.jbuilder', :status => 200
	end


	private

	# def set_cors
	# 	response.headers["Access-Control-Allow-Origin"] = "*"
	# 	# response.headers["Access-Control-Request-Method"] = "*"
	# end

	def user_params
		params.permit(*policy(User).user_attributes)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :find_record, :except => :create

	def create
		@user = User.new(user_params)
		authorize @user

		@user.save

		respond_to do |format|
			format.js
		end
	end

	def show
		@user = User.find(params[:id])
		authorize @user
		@expenses = @user.expenses

		if current_user.role.name == "admin"
			@users = User.all
		end
	end

	def user_details
		respond_to do |format|
			format.js
		end
	end

	def edit
		respond_to do |format|
			format.js
		end
	end

	def update
		@user.update_attributes(user_params)
		respond_to do |format|
			format.js
		end
	end

	def destroy
		@user.destroy

		respond_to do |format|
			format.js
		end
	end



	def report
		data = ReportService.generate_report_data(params, @user)

		if data.nil?
			data << "Wrong date params."
		end

		send_data ReportService.generate_pdf(data), filename: APP_CONFIG['report_file_name'], type: 'application/pdf', :disposition => "attachment"
	end


	private

	def user_params
		params.permit(*policy(User).user_attributes)
	end

	def find_record
		@user = User.find(params[:id])
		authorize @user
	end

end

app/views/users/_admin_users.html.erb
<%= javascript_include_tag "users/admin_users" %>
<%= javascript_include_tag "users/new_user_validation" %>

<div class="row">
	<div class="col-lg-4 col-md-4">
		<a id='add_user', class ='btn btn-primary' href="#">Add new user</a>
	</div>
</div>
<br/>

<div class="row">
	<div id="new_user", style="display:none;" class="col-sm-4 col-lg-4 col-md-4">
		<%= form_tag users_path(), :method => :post, :remote => true, :id => 'new_user_form', :style => "width: 500px;" do %>
			<div class="row">
				<div class="col-lg-6 col-md-6">
					<%= text_field_tag(:first_name, params[:first_name], :class => 'form-control', :placeholder => 'First Name', :required => true, :autofocus => true, :id => "new_user_first_name") %>
				</div>
				<div class="col-lg-6 col-md-6">
					<%= text_field_tag(:last_name, params[:last_name], :class => 'form-control', :placeholder => 'Last Name', :required => true, :id => 'new_user_last_name') %>
				</div>
			</div>
			<br/>

			<div class="row">
				<div class="col-lg-6 col-md-6">
					<%= text_field_tag(:email, params[:email], :class => 'form-control', :placeholder => 'user@isp.net', :required => true ) %>
				</div>
				<div class="col-lg-6 col-md-6">
					<%= select_tag(:role_id, options_for_select(Role.all.map{|r| [r.name, r.id]}), :class => 'form-control' ) %>
				</div>
			</div>
			<br/>

			<div class="row">
				<div class="col-lg-6 col-md-6">
					<%= text_field_tag(:password, params[:password], :class => 'form-control', :placeholder => 'Password min. 4 chars', :type => 'password') %>
				</div>
				<div class="col-lg-6 col-md-6">
					<%= text_field_tag(:password_confirmation, params[:password_confirmation], :class => 'form-control', :placeholder => 'Password again', :type => 'password') %>
				</div>
			</div>
			<br/>
			<div class="row">
				<div class="col-lg-6 col-md-6 text-center">
					<a href="#" id="close_new_user", class="btn btn-sm btn-danger">Cancel</a>
				</div>
				<div class="col-lg-6 col-md-6 text-center">
					<%= button_tag( "Add", :class => "btn btn-sm btn-primary" ) %>
				</div>
			</div>
		<% end %>
	</div>
</div>
<br/><br/>

<div class="table-container">
	<div class="col-md-12">
		<table class="table table-striped" id="users_table">
			<thead>
				<tr>
					<th>Email</th>
					<th>First Name</th>
					<th>Last Name</th>
					<th>Role</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody id="users_tbl_body">
				<% users.each do |u| %>
				<tr id='user_id_<%= "#{u.id}" %>'>
					<td><%= link_to u.email, user_path(u.id) %></td>
					<td><%= u.first_name %></td>
					<td><%= u.last_name %></td>
					<td><%= u.role.name %></td>
					<td>
						<%= link_to "Details", user_details_user_path(u.id), :method => :get, :remote => true, :class => "btn btn-success" %>
						<%= link_to "Edit", edit_user_path(u.id), :method => :get, :remote => true, :class => "btn btn-warning" %>
						<%= link_to "Delete", user_path(u.id), :method => :delete, :remote => true, :class => "btn btn-danger" %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/users/_edit_user.html.erb
<%= javascript_include_tag "users/edit_user_validation" %>


<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header edit_header">
			<button id="close_user_edit_modal" type="button" class="close" data-dismiss="modal" data-target="edit_user_modal">
				<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
			</button>
			<h4 class="modal-title">Edit user</h4>
		</div>
		<div class="modal-body">
			<%= form_tag user_path(user.id), :method => :put, :remote => true, :id => 'edit_user_form', :style => "width: 500px;" do %>
				<div class="row">
					<div class="col-lg-6 col-md-6">
						<%= text_field_tag(:first_name, user.first_name, :class => 'form-control', :required => true, :placeholder => 'First Name', :autofocus => true, :id => "edit_user_first_name") %>
					</div>
					<div class="col-lg-6 col-md-6">
						<%= text_field_tag(:last_name, user.last_name, :class => 'form-control', :required => true, :placeholder => 'Last Name', :id => 'edit_user_last_name') %>
					</div>
				</div>
				<br/>

				<div class="row">
					<div class="col-lg-6 col-md-6">
						<%= text_field_tag(:email, user.email, :class => 'form-control', :placeholder => 'user@isp.net', :required => true ) %>
					</div>
					<div class="col-lg-6 col-md-6">
						<%= select_tag(:role_id, options_for_select(Role.all.map{|r| [r.name, r.id]}, :selected => @user.role.id ), :class => 'form-control' ) %>
					</div>
				</div>
				<br/>
				<div class="row">
					<div class="col-lg-6 col-md-6 text-center">
						<button id="close_edit_user_modal" type="button" class="btn btn-sm btn-danger" data-dismiss="modal" data-target="edit_user_modal">Cancel</button>
					</div>
					<div class="col-lg-6 col-md-6 text-center">
						<%= button_tag( "Update", :class => "btn btn-sm btn-primary" ) %>
					</div>
				</div>
			<% end %>

		</div>
	</div>
</div>

app/views/users/_new_user_row.html.erb
<tr id='user_id_<%= "#{@user.id}" %>'>
	<td><%= link_to @user.email, user_path(@user.id) %></td>
	<td><%= @user.first_name %></td>
	<td><%= @user.last_name %></td>
	<td><%= @user.role.name %></td>
	<td>
		<%= link_to "Details", user_details_user_path(@user.id), :method => :get, :remote => true, :class => "btn btn-success" %>
		<%= link_to "Edit", edit_user_path(@user.id), :method => :get, :remote => true, :class => "btn btn-warning" %>
		<%= link_to "Delete", user_path(@user.id), :method => :delete, :remote => true, :class => "btn btn-danger" %>
	</td>
</tr>

app/views/users/_user_details.html.erb
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header details_header">
			<button id="close_modal" type="button" class="close" data-dismiss="modal" data-target="show_expense_modal">
				<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
			</button>
			<h4 class="modal-title">User details</h4>
		</div>
		<div class="modal-body">
			<p>First Name: <%= user.first_name %></p>
			<p>Last Name: <%= user.last_name %></p>
			<p>Email: <%= user.email %></p>
			<p>Role: <%= user.role.name %></p>
			<p>Joined: <%= user.created_at.strftime("%Y-%m-%d")%></p>
			<br/>
			<%= link_to "#{user.first_name}'s expenses", user_path(user.id) %>
		</div>
	</div>
</div>

app/views/users/create.js.erb
<% if @user.errors.any? %>
	alert('Error: <%="#{@user.errors.full_messages.to_sentence}"%>');
<% else %>
	// alert("New user successfully added.");
	$("#close_new_user").trigger("click");
	$("#users_tbl_body").append("<%= j render(:partial => 'new_user_row', :object => @user) %>");
<% end %>

app/views/users/destroy.js.erb
<% if @user.errors.any? %>
	alert('Error: <%="#{@user.errors.full_messages.to_sentence}"%>');
	return false;
<% else %>
	$("#user_id_<%= @user.id %>").remove();
<% end %>

app/views/users/edit.js.erb
$("#edit_user_modal").html("<%= j render(:partial => 'edit_user', :locals => { :user => @user } ) %>");
$("#edit_user_modal").modal("show");

app/views/users/show.html.erb
<%= javascript_include_tag "users/show" %>
<%= javascript_include_tag "expenses/new_expense_validation" %>

<div class="container">
	<h4>Welcome <strong><%= "#{current_user.first_name} #{current_user.last_name}" %></strong>, you're logged in as <strong><%= current_user.role.name %></strong> user.</h4>
	<hr>

	<div class="row">
		<ul class="nav nav-tabs">
			<li class="active">
			<a href="#expenses" data-toggle="tab">
			<% if policy(current_user).is_admin? %>
				<%= "#{@user.first_name}'s expenses" %>
			<% else %>
				My expenses
			<% end %>
			</a></li>

			<% if policy(current_user).is_admin? %>
				<li><a href="#users" data-toggle="tab">Users</a></li>
			<% end %>
		</ul>
	</div>

	<div class="tab-content">
		<div class="tab-pane fade in active" id="expenses">
			<br/>
			<div class="row">
				<div class="col-lg-4 col-md-4">
					<a id='add_expense', class ='btn btn-primary' href="#">Add new expense</a>
				</div>

				<div class="col-lg-1 col-md-1">
					<label for="filter">Filter by:</label>
				</div>
				<div class="col-lg-2 col-md-2">
					<%= select_tag(:filter, options_for_select(Filter.all.map{|f| [f.name, f.id]}), :class => 'form-control'  ) %>
					<%= hidden_field_tag :filter_url, filter_user_expenses_path(@user) %>
				</div>

				<div class="col-lg-2 col-md-2 col-md-offset-2 col-lg-offset-2">
					<a id='report_btn', class ='btn btn-success' href="#">Report</a>
				</div>
			</div>
			<br/>

			<div class="row">
				<div id="new_expense", style="display:none;" class="col-sm-4 col-lg-4 col-md-4">
					<%= render :partial => 'expenses/new', :locals => { :user => @user } %>
				</div>

				<div id="report", style="display:none;" class="col-lg-4 col-md-4 col-md-offset-8 col-lg-offset-8">
					<%= render :partial => 'expenses/report', :locals => { :user => @user } %>
				</div>
			</div>
			<br/>

			<div class="table-container">
				<div class="col-md-12">
					<table class="table table-striped" id="regular_user_expenses_table">
						<thead>
							<tr>
								<th>Description</th>
								<th>Amount</th>
								<th>Date</th>
								<th>Time</th>
								<th>Comment</th>
								<th>Actions</th>
							</tr>
						</thead>
						<tbody id="regular_user_expenses_tbl_body">
							<% @expenses.each do |e| %>
							<tr id='expense_id_<%= "#{e.id}" %>'>
								<td><%= e.description %></td>
								<td><%= e.amount %></td>
								<td><%= e.date %></td>
								<td><%= e.time.strftime("%H:%M") %></td>
								<td><%= truncate(e.comment, :length => 35, :separator => "") %></td>
								<td>
									<%= link_to "Show", user_expense_path(@user, e), :method => :get, :remote => true, :class => "btn btn-success" %>
									<%= link_to "Edit", edit_user_expense_path(@user, e), :method => :get, :remote => true, :class => "btn btn-warning" %>
									<%= link_to "Delete", user_expense_path(@user,e), :method => :delete, :remote => true, :class => "btn btn-danger" %>
								</td>
							</tr>
							<% end %>
						</tbody>
					</table>
				</div>
			</div>
		</div>

		<% if policy(current_user).is_admin? %>
			<div class="tab-pane fade" id="users">
				<br/>
				<%= render :partial => 'admin_users', :locals => { :users => @users }%>
			</div>
		<% end %>

	</div>
</div>

<div id="show_expense_modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
</div>

<div id="edit_expense_modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
</div>

<% if policy(current_user).is_admin? %>
	<div id="show_user_modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
	</div>

	<div id="edit_user_modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
	</div>
<% end %>

app/views/users/update.js.erb
<% if @user.errors.any? %>
	alert('Error: <%="#{@user.errors.full_messages.to_sentence}"%>');
<% else %>
	$("#edit_user_modal").modal("hide");
	$("#user_id_<%= @user.id %>").replaceWith("<%= j render(:partial => 'new_user_row', :object => @user) %>");
<% end %>

app/views/users/user_details.js.erb
$("#show_user_modal").html("<%= j render(:partial => 'user_details', :locals => { :user => @user } ) %>");
$("#show_user_modal").modal("show");