config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

	root 'home#index'
	get 'logout' => 'sessions#destroy', :as => 'logout'

	resources :signup, :only => [:new, :create]

	resources :sessions, :only => [:new, :create]

	resources :users, :except => [:index, :new] do
		resources :expenses, :except => [:index, :new] do
			collection do
				get :filter
			end
		end

		member do
			get :report
			get :user_details
		end
	end

	#API
	namespace :api, :defaults => { :format => 'json'} do
		scope module: :v1, :constraints => ApiConstraints.new(version: 1, default: true) do

			resources :sessions, :only => [:create, :destroy]

			resources :users, :except => [:new, :edit] do

				collection do
					get :loggedin_user
				end

				resources :expenses, :except => [:new, :edit] do
					collection do
						get :filter
					end
				end

				member do
					get :report
				end
			end

		end
	end

end

app/controllers/api/v1/expenses_controller.rb
class Api::V1::ExpensesController < Api::V1::ApplicationController

	before_action :find_parent
	before_action :find_record, :except => [:create, :index, :filter]

	def create
		@expense = Expense.new(expense_params)
		authorize @expense

		if @expense.save
			render 'create.json.jbuilder', :status => 201
		else
			render :json => { :message => @expense.errors.full_messages.to_sentence }, :status => 409
		end
	end

	def update
		if @expense.update_attributes(expense_params)
			render 'update.json.jbuilder', :status => 200
		else
			render :json => { :message => @expense.errors.full_messages.to_sentence }, :status => 409
		end
	end

	def destroy
		if @expense.destroy
			render :json => { :message => "Expense deleted." }, :status => 200
		else
			render :json => { :message => @expense.errors.full_messages.to_sentence }, :status => 409
		end
	end

	def show
		render 'show.json.jbuilder', :status => 200
	end

	def index
		@expenses = @user.expenses
		render 'index.json.jbuilder', :status => 200
	end

	def filter
		@filter_result = ExpensesFilterService.get_filter_results(params[:type], @user)

		if !@filter_result.nil?
			render 'filter.json.jbuilder', :status => 200
		else
			render :status => 204
		end
	end


	private

	def find_record
		@expense = Expense.find(params[:id])
		authorize @expense
	end

	def find_parent
		@user = User.find(params[:user_id])
		authorize @user, :can_manage_expenses?
	end

	def expense_params
		params.permit(*policy(Expense).expense_attributes)
	end

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController

	before_filter :find_parent
	before_filter :find_record, :except => [:create, :filter]

	def show
		respond_to do |format|
			format.js
		end
	end

	def create
		@expense = Expense.new(expense_params)
		@expense.user_id = @user.id
		authorize @expense
		@expense.save

		respond_to do |format|
			format.js
		end
	end

	def edit
		respond_to do |format|
			format.js
		end
	end

	def update
		@expense.update_attributes(expense_params)
		respond_to do |format|
			format.js
		end
	end

	def destroy
		@expense.destroy

		respond_to do |format|
			format.js
		end
	end

	def filter
		@filter_result = ExpensesFilterService.get_filter_results(params[:filter_id], @user)

		respond_to do |format|
			format.js
		end
	end

	private

	def find_parent
		@user = User.find(params[:user_id])
		authorize @user, :can_manage_expenses?
	end

	def find_record
		@expense = Expense.find(params[:id])
		authorize @expense
	end

	def expense_params
		params.permit(*policy(Expense).expense_attributes)
	end

end

app/views/expenses/_edit_expense.html.erb
<%= javascript_include_tag "expenses/edit_expense_datetime_pickers" %>
<%= javascript_include_tag "expenses/edit_expense_validation" %>


<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header edit_header">
			<button id="close_edit_modal" type="button" class="close" data-dismiss="modal" data-target="edit_expense_modal">
				<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
			</button>
			<h4 class="modal-title">Edit expense</h4>
		</div>
		<div class="modal-body">
			<%= form_tag user_expense_path(@user, @expense), :method => :put, :remote => true, :id => 'edit_expense_form', :class => 'form-signin' do %>

			<div class="row">
				<div class="col-lg-6 col-md-6">
					<%= text_field_tag(:description, @expense.description, :class => 'form-control', :placeholder => 'Description', :required => true, :autofocus => true, :id => "edit_ex_description") %>
				</div>
				<div class="col-lg-6 col-md-6">
					<%= text_field_tag(:amount, @expense.amount, :class => 'form-control', :placeholder => 'Amount', :required => true, :id => 'edit_ex_amount') %>
				</div>
			</div>
			<br/>

			<div class="row">
				<div class="col-lg-6 col-md-6">
					<%= text_field_tag(:date, @expense.date, :class => 'form-control datepicker', :placeholder => 'YYYY-MM-DD', :required => true, :id => 'datepicker_edit', :name => 'date' ) %>
					<!-- <input type='text' class="form-control" id='datepicker' /> -->
				</div>
				<div class="col-lg-6 col-md-6">
					<%= text_field_tag(:time, @expense.time.strftime("%H:%M"), :class => 'form-control datepicker', :placeholder => 'HH:mm', :required => true, :id => 'timepicker_edit', :name => 'time' ) %>
					<!-- <input type='text' class="form-control" id='timepicker' /> -->
				</div>
			</div>
			<br/>

			<div class="row">
				<div class="col-lg-6 col-mg-6">
					<%= text_area_tag( :comment, @expense.comment, :rows => 4, :cols => 34, :placeholder => 'Comment', :id => "edit_ex_comment") %>
				</div>
			</div>
			<br/><br/>

			<div class="row">
				<div class="col-lg-6 col-md-6 text-center">
					<button id="close_edit_modal" type="button" class="btn btn-sm btn-danger" data-dismiss="modal" data-target="edit_expense_modal">Cancel</button>
				</div>
				<div class="col-lg-6 col-md-6 text-center">
					<%= button_tag( "Update", :class => "btn btn-sm btn-primary" ) %>
				</div>
			</div>

			<% end %>
		</div>
	</div>
</div>

app/views/expenses/_expense_filter_result.html.erb
<% filter_result.each do |fr| %>
	<tr id='expense_id_<%= "#{fr.id}" %>'>
		<td><%= fr.description %></td>
		<td><%= fr.amount %></td>
		<td><%= fr.date %></td>
		<td><%= fr.time.strftime("%H:%M") %></td>
		<td><%= truncate(fr.comment, :length => 35, :separator => "") %></td>
		<td>
			<%= link_to "Show", user_expense_path(fr.user_id, fr), :method => :get, :remote => true, :class => "btn btn-success" %>
			<%= link_to "Edit", edit_user_expense_path(fr.user_id, fr), :remote => true, :class => "btn btn-warning" %>
			<%= link_to "Delete", user_expense_path(fr.user_id, fr), :method => :delete, :remote => true, :class => "btn btn-danger" %>
		</td>
	</tr>
<% end %>

app/views/expenses/_new.html.erb
<%= form_tag user_expenses_path(user.id), :method => :post, :remote => true, :id => 'new_expense_form', :class => 'form-signin' do %>

	<div class="row">
		<div class="col-lg-6 col-md-6">
			<%= text_field_tag(:description, params[:description], :class => 'form-control', :placeholder => 'Description', :required => true, :autofocus => true, :id => "new_ex_description") %>
		</div>
		<div class="col-lg-6 col-md-6">
			<%= text_field_tag(:amount, params[:amount], :class => 'form-control', :placeholder => 'Amount', :required => true, :id => 'new_ex_amount') %>
		</div>
	</div>
	<br/>

	<div class="row">
		<div class="col-lg-6 col-md-6">
			<%= text_field_tag(:date, params[:date], :class => 'form-control', :placeholder => 'YYYY-MM-DD', :required => true, :id => 'datepicker', :name => 'date' ) %>
			<!-- <input type='text' class="form-control" id='datepicker' /> -->
		</div>
		<div class="col-lg-6 col-md-6">
			<%= text_field_tag(:time, params[:time], :class => 'form-control', :placeholder => 'HH:mm', :required => true, :id => 'timepicker', :name => 'time' ) %>
			<!-- <input type='text' class="form-control" id='timepicker' /> -->
		</div>
	</div>
	<br/>

	<div class="row">
		<div class="col-lg-6 col-mg-6">
			<%= text_area_tag( :comment, nil, :rows => 4, :cols => 34, :placeholder => 'Comment', :id => "new_ex_comment") %>
		</div>
	</div>
	<br/><br/>

	<div class="row">
		<div class="col-lg-6 col-md-6 text-center">
			<a href="#" id="close_new_expense", class="btn btn-sm btn-danger">Cancel</a>
		</div>
		<div class="col-lg-6 col-md-6 text-center">
			<%= button_tag( "Add", :class => "btn btn-sm btn-primary" ) %>
		</div>
	</div>

<% end %>

app/views/expenses/_new_expense_row.html.erb
<tr id='expense_id_<%= "#{@expense.id}" %>'>
	<td><%= @expense.description %></td>
	<td><%= @expense.amount %></td>
	<td><%= @expense.date %></td>
	<td><%= @expense.time.strftime("%H:%M") %></td>
	<td><%= truncate(@expense.comment, :length => 35, :separator => "") %></td>
	<td>
		<%= link_to "Show", user_expense_path(@expense.user_id, @expense), :method => :get, :remote => true, :class => "btn btn-success" %>
		<%= link_to "Edit", edit_user_expense_path(@expense.user_id, @expense), :method => :get, :remote => true, :class => "btn btn-warning" %>
		<%= link_to "Delete", user_expense_path(@expense.user_id, @expense), :method => :delete, :remote => true, :class => "btn btn-danger" %>
	</td>
</tr>

app/views/expenses/_report.html.erb
<%= javascript_include_tag "expenses/report_validation" %>

<%= form_tag report_user_path(:id => user.id, :format => :pdf), :method => :get, :id => 'report_form', :class => 'form-signin' do %>
	<div class="row">
		<div class="col-lg-6 col-md-6 col-lg-offset-1 col-md-offset-1">
			<label for="week">Select week:</label>
			<%= text_field_tag(:week, params[:week], :class => 'form-control datepicker', :placeholder => 'YYYY-MM-DD', :required => true, :id => 'datepicker_week', :name => 'week' ) %>
		</div>
	</div>
	<br/>

	<div class="row">
		<div class="col-lg-2 col-md-2  col-lg-offset-1 col-md-offset-1 text-center">
			<a href="#" id="close_report", class="btn btn-sm btn-danger">Cancel</a>
		</div>
		<div class="col-lg-2 col-md-2 col-lg-offset-1 col-md-offset-1">
			<%= button_tag("Print", :class => 'btn btn-sm btn-primary') %>
		</div>
	</div>
<% end %>

app/views/expenses/_show_expense.html.erb
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header details_header">
			<button id="close_modal" type="button" class="close" data-dismiss="modal" data-target="show_expense_modal">
				<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
			</button>
			<h4 class="modal-title">Expense details</h4>
		</div>
		<div class="modal-body">
			<p>Description: <%= expense.description %></p>
			<p>Amount: <%= expense.amount %></p>
			<p>Date: <%= expense.date %></p>
			<p>Time: <%= expense.time.strftime("%H:%M") %></p>
			<p>Comment: <%= expense.comment %></p>
		</div>
	</div>
</div>

app/views/expenses/create.js.erb
<% if @expense.errors.any? %>
	alert('Error: <%="#{@expense.errors.full_messages.to_sentence}"%>');
<% else %>
	//alert("New expense successfully added.");
	$("#close_new_expense").trigger("click");
	$("#regular_user_expenses_tbl_body").append("<%= j render(:partial => 'new_expense_row', :object => @expense) %>");
<% end %>

app/views/expenses/destroy.js.erb
<% if @expense.errors.any? %>
	alert('Error: <%="#{@expense.errors.full_messages.to_sentence}"%>');
	return false;
<% else %>
	$("#expense_id_<%= @expense.id %>").remove();
<% end %>

app/views/expenses/edit.js.erb
$("#edit_expense_modal").html("<%= j render(:partial => 'edit_expense', :locals => { :user => @user, :expense => @expense } ) %>");
$("#edit_expense_modal").modal("show");

app/views/expenses/filter.js.erb
<% if @filter_result.present? %>
	$("#regular_user_expenses_tbl_body").html("<%= j render(:partial => 'expense_filter_result', :locals => { :filter_result => @filter_result }) %>");
<% else %>
	$("#regular_user_expenses_tbl_body").html("");
<% end %>

app/views/expenses/show.js.erb
$("#show_expense_modal").html("<%= j render(:partial => 'show_expense', :locals => { :user => @user, :expense => @expense } ) %>");
$("#show_expense_modal").modal("show");

app/views/expenses/update.js.erb
<% if @expense.errors.any? %>
	alert('Error: <%="#{@expense.errors.full_messages.to_sentence}"%>');
<% else %>
	$("#edit_expense_modal").modal("hide");
	$("#expense_id_<%= @expense.id %>").replaceWith("<%= j render(:partial => 'new_expense_row', :object => @expense) %>");
<% end %>