config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

	root 'home#index'
	get 'logout' => 'sessions#destroy', :as => 'logout'

	resources :signup, :only => [:new, :create]

	resources :sessions, :only => [:new, :create]

	resources :users, :except => [:index, :new] do
		resources :expenses, :except => [:index, :new] do
			collection do
				get :filter
			end
		end

		member do
			get :report
			get :user_details
		end
	end

	#API
	namespace :api, :defaults => { :format => 'json'} do
		scope module: :v1, :constraints => ApiConstraints.new(version: 1, default: true) do

			resources :sessions, :only => [:create, :destroy]

			resources :users, :except => [:new, :edit] do

				collection do
					get :loggedin_user
				end

				resources :expenses, :except => [:new, :edit] do
					collection do
						get :filter
					end
				end

				member do
					get :report
				end
			end

		end
	end

end

app/views/layouts/_flash_messages.html.erb
<% unless flash.empty? %>
<div class="modal-dialog">
	<% flash.each do |name, msg| %>
	<div class="text-center alert alert-<%= name == "notice" ? "success" : "danger" %>">
		<button type="button" class="close" data-dismiss="alert">×</button>
		<% msg = *msg %>
		<% msg.each do |item| %>
		<p><%= item %></p>
		<% end %>
	</div>
	<% end %>
</div>
<% end %>
<script>
	$(".alert").delay(300).addClass("in").fadeOut(5000);
</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container">
		<div class="row">
			<h4>Expenses Tracker App Prototype</h4>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="header">

	<nav class="navbar navbar-default" role="navigation">

		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<% if user_logged_in? %>
					<%= link_to 'Home', user_path(current_user.id), :class => 'navbar-brand' %>
				<%	else %>
					<%= link_to 'Home', root_path, :class => 'navbar-brand' %>
				<% end %>
			</div>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
					<% if user_logged_in? %>
					<li class="dropdown">
						<a href="#" data-toggle="dropdown" class="dropdown-toggle">Hi <%= current_user.first_name %> <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><%#= link_to 'Edit profile','' %></li>
							<li><%= link_to 'Sign out', '/logout' %></li>
						</ul>
					</li>
					<% else %>
						<li><%= link_to 'Create account', new_signup_path() %></li>
						<li><%= link_to 'Sign in', new_session_path() %></li>
					<% end %>
				</ul>

			</div>
		</div>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>ExpensesTrackerApp</title>

	<%= stylesheet_link_tag "//fonts.googleapis.com/css?family=Raleway:500,600,700,800,900,400,300", type: 'text/css' %>
	<%= stylesheet_link_tag    'application', media: 'all' %>
	<%= javascript_include_tag 'application' %>
	<%= csrf_meta_tags %>
</head>

<body>

	<div id="container">
		<div id="header">
			<%= render 'layouts/header' %>
		</div>
		<div id="body">
			<%= render 'layouts/flash_messages' %>
			<%= yield %>
		</div>
		<div id="footer">
			<%= render 'layouts/footer' %>
		</div>
	</div>

</body>
</html>